### PR TITLE
hardcoded skeleton for html

### PR DESCRIPTION
**Pull request by ZakkFast**
Hardcoded skele for HTML to be used as a reference for JS. ID NAMES ARE NOT FINAL, THEY CAN BE CHANGED!

### CODE REVIEW

**Review by SJROHRXD — COMMENTED** [review]
yep

**Comment by SJROHRXD** [comment]
yeppp

**Comment by rashir01** [comment]
dfaf

**Review by SJROHRXD — APPROVED** [review]
reviewed

**Pull request merged**
